
package cis.bir.publ._2014._07;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import org.tempuri.UslugaBIRzewnPubl;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-06T19:36:03.981+01:00
 * Generated source version: 3.2.7
 *
 */
public final class IUslugaBIRzewnPubl_E3_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "UslugaBIRzewnPubl");

    private IUslugaBIRzewnPubl_E3_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UslugaBIRzewnPubl.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        UslugaBIRzewnPubl ss = new UslugaBIRzewnPubl(wsdlURL, SERVICE_NAME);
        IUslugaBIRzewnPubl port = ss.getE3();

        {
        System.out.println("Invoking setValue...");
        java.lang.String _setValue_pNazwaParametru = "";
        java.lang.String _setValue_pWartoscParametru = "";
        java.lang.String _setValue__return = port.setValue(_setValue_pNazwaParametru, _setValue_pWartoscParametru);
        System.out.println("setValue.result=" + _setValue__return);


        }
        {
        System.out.println("Invoking daneSzukaj...");
        cis.bir.publ._2014._07.datacontract.ParametryWyszukiwania _daneSzukaj_pParametryWyszukiwania = null;
        java.lang.String _daneSzukaj__return = port.daneSzukaj(_daneSzukaj_pParametryWyszukiwania);
        System.out.println("daneSzukaj.result=" + _daneSzukaj__return);


        }
        {
        System.out.println("Invoking sprawdzCaptcha...");
        java.lang.String _sprawdzCaptcha_pCaptcha = "";
        java.lang.Boolean _sprawdzCaptcha__return = port.sprawdzCaptcha(_sprawdzCaptcha_pCaptcha);
        System.out.println("sprawdzCaptcha.result=" + _sprawdzCaptcha__return);


        }
        {
        System.out.println("Invoking getValue...");
        java.lang.String _getValue_pNazwaParametru = "";
        java.lang.String _getValue__return = port.getValue(_getValue_pNazwaParametru);
        System.out.println("getValue.result=" + _getValue__return);


        }
        {
        System.out.println("Invoking zaloguj...");
        java.lang.String _zaloguj_pKluczUzytkownika = "";
        java.lang.String _zaloguj__return = port.zaloguj(_zaloguj_pKluczUzytkownika);
        System.out.println("zaloguj.result=" + _zaloguj__return);


        }
        {
        System.out.println("Invoking wyloguj...");
        java.lang.String _wyloguj_pIdentyfikatorSesji = "";
        java.lang.Boolean _wyloguj__return = port.wyloguj(_wyloguj_pIdentyfikatorSesji);
        System.out.println("wyloguj.result=" + _wyloguj__return);


        }
        {
        System.out.println("Invoking daneKomunikat...");
        java.lang.String _daneKomunikat__return = port.daneKomunikat();
        System.out.println("daneKomunikat.result=" + _daneKomunikat__return);


        }
        {
        System.out.println("Invoking pobierzCaptcha...");
        java.lang.String _pobierzCaptcha__return = port.pobierzCaptcha();
        System.out.println("pobierzCaptcha.result=" + _pobierzCaptcha__return);


        }
        {
        System.out.println("Invoking danePobierzPelnyRaport...");
        java.lang.String _danePobierzPelnyRaport_pRegon = "";
        java.lang.String _danePobierzPelnyRaport_pNazwaRaportu = "";
        java.lang.String _danePobierzPelnyRaport__return = port.danePobierzPelnyRaport(_danePobierzPelnyRaport_pRegon, _danePobierzPelnyRaport_pNazwaRaportu);
        System.out.println("danePobierzPelnyRaport.result=" + _danePobierzPelnyRaport__return);


        }

        System.exit(0);
    }

}
